version: '3.8'
services:
  app:
    container_name: docker-meetings
    image: docker_meetings
    build: ./
    ports:
      - "8082:8080"
    depends_on:
      - postgresqldb
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresqldb:5432/meetingsdb?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&stringtype=unspecified
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=DB
      - SPRING_JPA_HIBERNATE_DDL_AUTO=none
  postgresqldb:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=DB
      - POSTGRES_DB=meetingsdb
      - PGDATA=./Program Files/PostgreSQL/14/data

volumes:
  postgresqldb: {}